# import tkinter
# window = tkinter.Tk()
# frame = tkinter.Frame(window)
# frame.pack()
# first = tkinter.Label(frame, text='First label',foreground="white",background="black",font=("Arial",100))
# first.pack()
# second = tkinter.Label(frame, text='Second label',foreground="yellow",background="red",font=("Arial",100))
# second.pack()
# third = tkinter.Label(frame, text='Third label',foreground="blue",background="purple",font=("Arial",100))
# third.pack()
# window.mainloop()


import tkinter
window = tkinter.Tk()
frame = tkinter.Frame(window)
frame.pack()
frame2 = tkinter.Frame(window, borderwidth=4, relief=tkinter.GROOVE)
frame2.pack()
first = tkinter.Label(frame, text='First label')
first.pack()
second = tkinter.Label(frame2, text='Second label')
second.pack()
third = tkinter.Label(frame2, text='Third label')
third.pack()
window.mainloop()